name: location_ios
description: iOS implementation of the location plugin
homepage: https://docs.page/Lyokone/flutterlocation
repository: https://github.com/Lyokone/flutterlocation
version: 6.0.0-dev.1

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: location
    platforms:
      ios:
        pluginClass: LocationPlugin
        dartPluginClass: LocationIOS

dependencies:
  flutter:
    sdk: flutter
  location_platform_interface:
    git:
      url: https://github.com/Eu-Arthur/flutter_location_platform_interface.git
dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^3.1.5
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.0
